### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by moll** [rahvaalgatus/vali#1]
Mänguvalimiste leht on üleval https://vali.rahvaalgatus.ee ja peaks hõlmama endas kõike esialgu plaanitut:
- Valimiste loomist koos kandidaatide ja lubatud valijate lisamisega.
- Hääletamist ja digihäälte CSV allalaadimist.
- Paberhäälte lisamist
- Lihtsat tulemuste vaatamist, mis võtab arvesse paberhääli
- Valimiste algus- ja lõpukuupäeva

Sisselogimine sai hetkel tehtud paroolipõhiseks. Seda kolmel põhjusel:
- Seda oli tunduvalt lihtsam implementeerida kui isikukoodiga sisselogimist.
- Lubab kontosid jagada, kui tundi annab asendusõpetaja.
- Ei pidanud implementeerima keerulisemat õigustesüsteemi, kus valimiste omanik saab haldusõigusi teistega jagada.

Kõik valimised on hetkel avalikud, v.a kandidaatide isikukoodid ja hääled. Vastavalt vajadusele saab hiljem lisada ka  avalikustamata valimiste või peidetud valimiste funktsionaalsust.

Valimisteleht kasutab lansseerimiseni digiallkirjastamise testkeskkonda. Seal saab testida SK Mobiil-Id ja Smart-Id testkontodega:
- https://github.com/SK-EID/MID/wiki/Test-number-for-automated-testing-in-DEMO
- https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#demo-parameters

**Comment by moll** [comment]
Lisada:
- [x] Tervituslõik esilehele.
- [x] Kasutatud fraasid Google Spreadsheeti.
- [x] Google Analytics

**Comment by moll** [comment]
Fraasid on nüüd Google Spreadsheetis: https://docs.google.com/spreadsheets/d/1m658H8M4lmYNhauEb_oeyasGhgsHg4N1HIT7GMKwo7A/edit#gid=0 ja @infokujur -ile muutmisõigused antud. Lisasin valimiste lehele ka tervituslõigu. Leiab ta `elections_page.welcome` id alt.

GA jaoks ootan ligipääsu GA-s loodud saidile.

**Comment by infokujur** [comment]
GA kutse saadetud.

**Comment by moll** [comment]
Käes ja GA lisatud.

Kuna võib vist öelda, et MVP funktsionaalsus sai üles, siis panen praeguseks _issue_ kinni. Täienduste jaoks võime uusi _issue_-sid teha.

Meenutan igaks juhuks, et praegu kasutab server veel testimiseks mõeldud allkirjastamise teenuseid – a la Mobiil-Id töötab vaid neil, kes oma isikukoodi on SK-s registreerinud. Kui tõsiseks kasutamiseks läheb, lülitan päris allkirjastamisele ümber.

**Comment by moll** [comment]
Huvitav oleks teada, mida pärisvalimistel allkirjastatakse. Meil aga hetkel fraasi `Valin "Muusikute esindaja" kandidaadi Kim Mitchell (38001101234).` ehk `election_page.voting_signable` fraas tabelis.
